repos:
  - repo: local
    hooks:
      - id: run-tests
        name: Run Django tests
        entry: env DJANGO_SETTINGS_MODULE=link_lagbe.settings pytest --maxfail=1 --disable-warnings
        language: system
        types: [python]