repos:
  - repo: local
    hooks:
      - id: run-tests
        name: Run Django tests
        entry: env DJANGO_SETTINGS_MODULE=config.settings pytest --maxfail=1 --disable-warnings || true
        language: system
        types: [python]
        files: ^app/tests/.*\.py$