apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery
  namespace: linklagbe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: celery
  template:
    metadata:
      labels:
        app: celery
    spec:
      containers:
        - name: celery
          image: genesisblock1033/linkg_lagbe:latest
          command:  ["celery", "-A", "config", "worker", "-l", "info"]
          envFrom:
            - configMapRef:
                name: django-config
            - secretRef:
                name: django-secret

