apiVersion: apps/v1
kind: Deployment
metadata:
  name: link-lagbe
  namespace: linklagbe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: link-lagbe
  template:
    metadata:
      labels:
        app: link-lagbe
    spec:
      automountServiceAccountToken: false
      containers:
        - name: django
          image: genesisblock1033/linkg_lagbe:v3
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: django-config
            - secretRef:
                name: django-secret
          volumeMounts:
            - name: static-volume
              mountPath: /app/staticfiles   # Must match Django's STATIC_ROOT
          command: ["/bin/sh", "-c"]
          args:
            - |
              python3 manage.py collectstatic --noinput && \
              python3 manage.py migrate && \
              gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers=4 --threads=2 --timeout=120
          resources:
            requests:
              cpu: "250m"                  # 0.25 CPU core guaranteed
              memory: "512Mi"              # 512 MB guaranteed
              ephemeral-storage: "512Mi"   # Disk buffer for temp/static files
            limits:
              cpu: "500m"                  # Max 0.5 CPU core
              memory: "1Gi"                # Max 1 GB
              ephemeral-storage: "1Gi"     # Max temporary storage allowed
      volumes:
        - name: static-volume
          emptyDir: {}                     # Ephemeral volume for static files
