# Generated by Django 5.2.4 on 2025-08-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='linkclick',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='link',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterModelTable(
            name='link',
            table='link_lagbe_link',
        ),
        migrations.AlterModelTable(
            name='linkclick',
            table='link_lagbe_link_click',
        ),
    ]
