# Generated by Django 5.2.4 on 2025-08-16 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelTable(
            name='subscription',
            table='link_lagbe_subscription',
        ),
    ]
